version: "3.4"

networks:
  dev:
    driver: bridge

services:
  backend:
    image: docker.io/library/backend
    depends_on:
      - "db"
    container_name: backend-services
    ports:
      - "5183:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - app_data:/var/lib/postgres/data
    networks:
      - dev

volumes:
  app_data:
